### ISSUE TITLE
[Feature Request] Restore NekoX Custom api

### ISSUE THREAD

**Issue by AkiraOtosaka** [qwq233/Nullgram#1]
**Is your feature request related to a problem? Please describe.**
since unofficial has limitations like limiting to 250 channel and quicker chance for getting reported (i mean getting limits due to it)  

**Describe the solution you'd like**
restore old api
https://t.me/NekogramX/539

**Describe alternatives you've considered**

**Additional context**

**Comment by qwq233** [comment]
add as a hidden feature.
details see channel
