### ISSUE TITLE
[功能请求] Raised forward/delete limits to 1024 +commit

### ISSUE THREAD

**Issue by Shikopat** [qwq233/Nullgram#12]
### Why do you think you need this feature

https://github.com/NextAlone/Nagram/commit/f2b7959490c7e79ec6651fce56726fa367bccc53

 

### Describe the solution you'd like

forward work natively while delete is not. Thats why delete have a "slicer" for a list with the ids.
For folks who ask: "WTF your map value contain list of the lists" well, key can be zero (0), but it in theory can contain the ids (here they check if (newTaskId != 0)) so to avoid rewriting values in this map we just add new chunks with ids.
If they will restrict native forward in future i will add same slicer too. Limit 1024 just to have it. It can be upto 2 billions, but after your client need to send all these chunks (=requests) and you can get api bans (for 5-10min due use abuse their api).
So, when you wanna forward 800 messages OR delete them think that TG servers control your API rates for certain api calls.

**Comment by qwq233** [comment]
This may cause Telegram staff to make some restrictions on nullgram's api (such as you can only join 100 group chats or channels)
