### ISSUE TITLE
[feature] 拓展「下拉打开归档对话」功能 

### ISSUE THREAD

**Issue by Steve-Mr** [qwq233/Nullgram#145]
### Why do you think you need this feature

在 telegram 加入 stories 功能之后，在聊天列表下拉时如果有 story 会优先触发 story 栏的拓展，再次下拉才会进入已归档聊天列表。同时 story 通过点击也可以查看，下拉手势并不是唯一的入口。

### Describe the solution you'd like

拓展「下拉打开归档对话」功能使得在该选项打开的情况下，在聊天界面执行下滑动作时直接进入已归档聊天列表，不再触发 story 栏。

**Comment by qwq233** [comment]
咋close了

**Comment by Steve-Mr** [comment]
> 咋close了

有禁用 story 功能之后大概已经满足我需求了
