### ISSUE TITLE
Based Chin..

### ISSUE THREAD

**Issue by aicynide** [qwq233/Nullgram#156]
### Why do you think you need this feature

>Due to the fragmentation of the NekoX and Nekogram communities, and the serious problems with the main developers of NekoX and Nekogram1, I decided to make Nullgram to integrate both of their functions to avoid these problems.

Null used in computer programming for an uninitialized, undefined, empty, or meaningless value. In the name of Nullgram, the purpose is to express that there is no such bad things. Nullgram won't push FCM-Notification "nmsl"2 or somethings like that to your phone, won't send ads3 to channels, won't compete maliciously4 or publish malicious rumors about competitors

### Describe the solution you'd like

Lmao

**Comment by qwq233** [comment]
what do you mean
