### ISSUE TITLE
Publish APKs in GitHub releases

### ISSUE THREAD

**Issue by JohnBetaro** [qwq233/Nullgram#160]
### Why do you think you need this feature

I don't use Google Play Services at all, so I don't have the Play Store, I use Obtainium to get apps directly from GitHub and also auto update them without my interaction.

### Describe the solution you'd like

Publish APKs in GitHub release page on every new update, you already built them, so just upload the artifacts while creating a new release.

**Comment by qwq233** [comment]
@JohnBetaro https://t.me/NullgramCI
https://t.me/NullgramAPKs

**Comment by qwq233** [comment]
@JohnBetaro there's already a built-in auto update. it gets apk file from tg channel and get updated automatically

**Comment by qwq233** [comment]
yes and no
it will automatically check it but it will popup a window to mention you and you can choose to update or not
but it will use api from android 12+
