### ISSUE TITLE
[Bug] Unable to open chat page

### ISSUE THREAD

**Issue by SaltedFishesNG** [qwq233/Nullgram#166]
### Steps to reproduce

none

### Expected behaviour

proper functioning

### Actual behaviour

Open any dialog page and it flashes back

### Smartphone Information

SDK: 33
PRODUCT_NAME: meizu_17_N_CN
BOARD_NAME: kona
SUPPORTED_ABIS: arm64-v8a, armeabi-v7a, armeabi

### Nullgram Version

v10.2.0-preview-e8f8804(1645201316) arm64

### Version requirement

- [X] I am using latest debug CI version of Nullgram and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

[crash-top-qwq2333-nullgram-03-11_03-01-57.zip](https://github.com/qwq233/Nullgram/files/13243543/crash-top-qwq2333-nullgram-03-11_03-01-57.zip)

**Comment by SaltedFishesNG** [comment]
I used the logs captured by LogFox, and both versions, `Nullgram v10.2.0-preview-07034f6 (1645201319) arm64` and `Nullgram v10.2.0-preview-e8f8804 (1645201316) arm64`, have this problem, and the The logs are generally the same.

**Comment by SaltedFishesNG** [comment]
Members can customize the style and color of reply messages.
It is also possible to forward other people's messages and reply to them.

Personally, I think this may be the cause of the nullgram bug.

**Comment by qwq233** [comment]
fixed
