### ISSUE TITLE
[feature] Ads Filter for Channel Messages

### ISSUE THREAD

**Issue by Chigusa0w0** [qwq233/Nullgram#193]
### Why do you think you need this feature

Some Telegram channels currently employ bots to automatically send out ads in the form of channel messages. These ads are usually repetitive, annoying, or inappropriate, and can be seen multiple times per day per channel, totaling tens of times per day if several channels are subscribed.

### Describe the solution you'd like

One possible solution is to implement a keyword-based message filter which allows users to define the keywords they do not want to see. Nullgram may hide the message in case filters are triggered.

### Describe alternatives you've considered

1. Given the common form of advertising, a URL domain-based filter should also work.
2. If hiding a message from displaying is not possible (e.g., affect the read state, or chances of false positives), a possible alternative is to replace the message text to something like "Filtered message here" and remove the images only.
3. If Alt. 2 is also not feasible, another possibility is to apply the spoiler effect (click to reveal) universally on the message text and image, optionally with a different visual style than normal spoiler.

### Is your feature request related to a problem

This feature request is related and similar to #35, but targets at user/bot-generated channel messages (ads).

The filter can ignore messages in the comment sections or associated groups of channels, if this can reduce development effort, as human discussion participants are unlikely to send out ads.

**Comment by qwq233** [comment]
可能这几周给做了，最近一直忘了有人要这个功能
