### ISSUE TITLE
[Feature Request] Add to Fdroid

### ISSUE THREAD

**Issue by brnwlshubh** [qwq233/Nullgram#2]
Add the app on Fdroid.

**Comment by qwq233** [comment]
i checked their policy and it reads appcenter is not allowed but i still want to keep it so i won't release it on fdroid sry

**Comment by linsui** [comment]
AppCenter is licensed under MIT so it's allowed. Only com.microsoft.appcenter:appcenter-push is not allowed because it dependes on firebase. But of course Nullgram can't be added to F-Droid since it uses firebase and GMS. A FOSS flavor requires a lot work so I thought it won't be added.
