### ISSUE TITLE
Request: Remove tracker -- Google CrashLytics

### ISSUE THREAD

**Issue by bc6048** [qwq233/Nullgram#214]
### Steps to reproduce

With ClassyShark3xodus, I found Google CrashLytics imbedded. This app is a well build and highly versatile Telegram fork app, but as a FOSS software, I think removing all trackers would be more privacy friendly.

### Expected behaviour

null

### Actual behaviour

null

### Smartphone Information

Samsung A54

### Nullgram Version

v10.8.1

### Version requirement

- [X] I am using latest debug CI version of Nullgram and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

null

**Comment by qwq233** [comment]
nope
