### ISSUE TITLE
[Bug] 版权声明被错误移除 / Original copyright details removed wrongly

### ISSUE THREAD

**Issue by Young-Lord** [qwq233/Nullgram#219]
在 [2ce3cea](https://github.com/qwq233/Nullgram/commit/2ce3cea9b61fe50f1dfb83eb4b647e690ce0c6f9#diff-3d0ab360206eb4baf3d6817bb677139bcfdc0bdc36bf2d1e2f3b81dbf552ffee) 中，`TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java`头部的 GPL v2 版权声明 `Copyright Nikolai Kudashov, 2013-2020.` 被错误移除，并替换为 `Copyright (C) 2019-2024 qwq233 <qwq233@qwq2333.top>`。
虽然您对此文件有更改，但显然更正确的做法是保留此行版权声明，而且我看你在`TMessagesProj/src/`目录下的其他文件也都是保留了原有版权声明的。

P.S. `CONTRIBUTING.md`里这个`code header`是指什么，版权声明吗？我个人认为具体写清楚会比较好
P.P.S. `Compilation Guide`太旧了，而且有些不清楚（比如说那个`two android apps with application IDs`），感觉可以直接删了换成[指向上游的超链接](https://github.com/DrKLO/Telegram?tab=readme-ov-file#compilation-guide)

**Comment by qwq233** [comment]
@Young-Lord 1. as自动改的 我看看能不能调成保留 不能就不强求了 已经改了的就不改回去了太麻烦
2. 是 理论上as会自动加创建新文件 我加这条是怕有人删了
3. 构筑建议参考ci 文档我极少更新

**Comment by Young-Lord** [comment]
关于3，构建我是能跑起来的，但是由于 https://github.com/qwq233/Nullgram/commit/ba8cec7fbaa1390d418a06740705e54db8513af7 引入的签名校验 以及一些别的东西（不确定是 Firebase 还是 tg API_HASH），我觉得别人按照 ci 跑也不容易跑起来

**Comment by qwq233** [comment]
> 关于3，构建我是能跑起来的，但是由于 [ba8cec7](https://github.com/qwq233/Nullgram/commit/ba8cec7fbaa1390d418a06740705e54db8513af7) 引入的签名校验 以及一些别的东西（不确定是 Firebase 还是 tg API_HASH），我觉得别人按照 ci 跑也不容易跑起来

你提及的都不影响构筑，构筑只需要替换签名这些

**Comment by Young-Lord** [comment]
只是编译的话确实可以正常编译，但打开后 退出/白屏 对开发者来说还是会比较怪
（貌似有点 offtopic 了？）

**Comment by qwq233** [comment]
更新了部分文档，copyright不清楚怎么规范作用域，暂不处理了
