### ISSUE TITLE
[Bug] 当打开特定 Telegraph 文章的即时预览并加载图片时出现闪退

### ISSUE THREAD

**Issue by KaguYuuki** [qwq233/Nullgram#226]
### Steps to reproduce

1. 打开并登录 Nullgram 客户端
2. 打开 https://telegra.ph/中国GDP有望2035年超美-04-01 的即时预览

### Expected behaviour

正常显示即时预览并加载图片

### Actual behaviour

Nullgram 闪退

### Smartphone Information

- Device: Xiaomi 13 Ultra (2304FPN6DC)
- OS: Xiaomi HyperOS 
- Version: V1.0.24.3.25.DEV on Android 14

### Nullgram Version

Nullgram v10.9.1-dcb3a2e (1645201463) arm64 基于 Telegram 10.9.1 (4464)

### Version requirement

- [X] I am using latest debug CI version of Nullgram and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

[log-2024-04-01 (2).txt](https://github.com/qwq233/Nullgram/files/14824283/log-2024-04-01.2.txt)

**Comment by qwq233** [comment]
无法复现，方便提供下user id吗

**Comment by KaguYuuki** [comment]
> 无法复现，方便提供下user id吗

id:6682399948

顺便您是直接打开还是开即时预览？我是打开即时预览出现的问题。

**Comment by qwq233** [comment]
我等下处理，我在firebase看到详细的崩溃日志了
