### ISSUE TITLE
[Bug] Weird Dex Classes Found, Explanation Request

### ISSUE THREAD

**Issue by bc6048** [qwq233/Nullgram#243]
### Steps to reproduce

There are many weird dex classes found by Inure App, containing several uncomfortable words, like the following example shown in the appended image.
![Screenshot_20240515_192445_Inure](https://github.com/qwq233/Nullgram/assets/89716925/1a88cca0-9da9-4268-83ee-7e131f557af9)

### Expected behaviour

An explanation of the purpose of these weird dex classes is requested.

### Actual behaviour

Weird dex classes found.

### Smartphone Information

Samsung A54

### Nullgram Version

v10.12.0-a9bddd5

### Version requirement

- [X] I am using latest debug CI version of Nullgram and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

Null

**Comment by qwq233** [comment]
this is because obfuscation modifies their original names.
generally speaking, you don't need to worry about it.
