### ISSUE TITLE
[feature] 点击链接预览中的图片打开图片而非链接

### ISSUE THREAD

**Issue by Steve-Mr** [qwq233/Nullgram#245]
### Why do you think you need this feature

（如果没记错）在 [23 年 10 月 28 日的更新中](https://telegram.org/blog/reply-revolution) Telegram 引入了新的链接预览样式，其中点击链接预览中的图片不会打开图片，而是会直接跳转到链接内容。导致查看链接指向的图片比之前多了至少一次跳转，很多情况下并不方便。

### Describe the solution you'd like

点击链接预览中的图片使用 telegram 的图片查看器打开，（即与普通消息中的图片相同的处理方式），点击链接预览的其他部分打开链接。必要的话添加为可选开关。

**Comment by qwq233** [comment]
这个大概是什么版本有的 官方的版本号即可

**Comment by Steve-Mr** [comment]
是 10.2.0 引入的

**Comment by qwq233** [comment]
能不能给一些例子,就是会点击会直接打开链接的图片的链接. 不是很方便测试.

**Comment by Steve-Mr** [comment]
https://vxtwitter.com/rPrequelMemes/status/1799969426126598237
比如这样的 Twitter 链接，链接预览会有图片。

**Comment by Steve-Mr** [comment]
现在的版本似乎丢失了这个改动。  
另外关于这个功能还有一点建议，如果可以在带有图片的链接预览中将「点击图片」和「点击图片之外的链接预览」的动作区分开可能会更好一点？
![Image](https://github.com/user-attachments/assets/8c0b4a25-ebcf-46f0-b9c7-62acc6df183b)
比如以这里的截图为例，点击图片可以直接打开图片而非预览链接，然后点击链接预览其他部分（即颜色较深的部分）打开链接
