### ISSUE TITLE
[Bug] 打开超链接时有概率未响应

### ISSUE THREAD

**Issue by Akizon77** [qwq233/Nullgram#270]
### Steps to reproduce

1.打开超链接

### Expected behaviour

拉起浏览器

### Actual behaviour

**有概率**无响应
![image](https://github.com/qwq233/Nullgram/assets/64686663/3cae8dc0-8250-48d7-9502-c456f28caa8b)

### Smartphone Information

- 设备 红米 Note12 Turbo
- Android13
- MIUI14.0.19
- 浏览器 Chrome 126.0.6478.122 Android

### Nullgram Version

v10.14.3-dc2fb1a arm64

### Version requirement

- [ ] I am using latest debug CI version of Nullgram and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

[log-2024-07-10.txt / 384.11K](https://alist.akz.moe/d/Upload/2024/07/log-2024-07-10.txt?sign=ottkMMl0A6aAbitHTyJ_hv_isc6d4FbcOuAvnIwjRvs=:0)

[log-2024-07-10 (2).txt / 390.58K](https://alist.akz.moe/d/Upload/2024/07/log-2024-07-10%20(2).txt?sign=9J3kL_cimfSHz-hjApLIjQqf3ufTjtlfNFjD54c1YTQ=:0)

**Comment by qwq233** [comment]
你试试调低 https://t.me/nullsetting/e?r=modifyDownloadSpeed 看看还有没有该情况

**Comment by Akizon77** [comment]
> 你试试调低 https://t.me/nullsetting/e?r=modifyDownloadSpeed 看看还有没有该情况

`未知设定`

在设置找了一下，没找到类似于`提升下载速度`的选项

重新复现了几次，发现事件似乎没有被记录到日志里

关掉了`应用内打开浏览器`似乎能解决

**Comment by qwq233** [comment]
你方便提供你的user id吗 我这边可以在crashlytics看看有没有出现anr之类的事情

**Comment by Akizon77** [comment]
1977354088

**Comment by qwq233** [comment]
![image](https://github.com/user-attachments/assets/74e1d572-f596-4737-a419-e6a25b369b4a)
不出意外的话就是这东西的问题 我有空研究下吧

**Comment by qwq233** [comment]
感觉像是官方的webview的多标签页做的不是很好，等待官方修吧，~~我没研究明白~~
