### ISSUE TITLE
[Bug]flsah back

### ISSUE THREAD

**Issue by comeupgo** [qwq233/Nullgram#286]
### Steps to reproduce

I use a vivo phone and first open surfboard to use the proxy. Then, open the nullgram software, it will show that it is connecting, and then the software will crash.

### Expected behaviour

Everything works fine and can enter the software normally

### Actual behaviour

The software crashes and exits abnormally

### Smartphone Information

vivox90s
originos 4
Android 14

### Nullgram Version

v10.14.5-68edb16

### Version requirement

- [X] I am using latest debug CI version of Nullgram and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

[log-2024-08-14.txt](https://github.com/user-attachments/files/16602483/log-2024-08-14.txt)

**Comment by qwq233** [comment]
Have you tired this version?
https://t.me/NullgramCI/2760

**Comment by qwq233** [comment]
Also if you are not good at English, please just use Chinese.
Flash back doesn't mean crash.

And your user id of your telegram account please?
