### ISSUE TITLE
[Bug] 优化消息过滤的逻辑设计

### ISSUE THREAD

**Issue by sherlcok314159** [qwq233/Nullgram#330]
### Steps to reproduce

1. 找一个带有媒体资源（图片 or 视频）同时带有文字说明的消息
2. 在文字说明中加入需要被过滤的关键词
3. 然后就会发现消息的排版会变得十分诡异

如下图所示，第一张是正常发送不带文字说明的消息，第二张是加了需要被过滤的关键词

![图片](https://github.com/user-attachments/assets/e408894b-7d4a-46c6-9b36-347e24504e22)

![图片](https://github.com/user-attachments/assets/b2143f63-48f6-4eb2-8cb6-09a9b62a84ef)

### Expected behaviour

1. 不影响原来媒体的排版
2. 去除掉带有过滤关键词的文本消息

### Actual behaviour

1. 排版诡异，可能会丢失媒体
2. 需要被过滤的文本依然存在

### Smartphone Information

- OS: Android 12

### Nullgram Version

Nullgram v11.1.3-51cbf0b (1645201611) arm64 基于 Telegram 11.1.3 (5244)

### Version requirement

- [X] I am using latest debug CI version of Nullgram and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

这里的话直觉上可以对媒体消息进行判断，当发现包含关键词的时候，就将 text 或者 message 直接置空，然后再返回

同时补充一个优化逻辑设计的地方：

当我们发现某日该频道只有一个被过滤信息时，日期就会空空的显示在那里，比如

![图片](https://github.com/user-attachments/assets/8f44483f-72e6-45a8-85fd-8b798de255b7)

这个时候多加一步判断就会好很多

**Comment by qwq233** [comment]
？
