### ISSUE TITLE
[Bug] 'Official' icon not working

### ISSUE THREAD

**Issue by andrew1-1** [qwq233/Nullgram#336]
### Steps to reproduce

1. Open Nullgram
2. Go to Settings
3. Click on 'Chat Settings'
4. Scroll down to 'App Icon'
4. Select the 'Official' icon

### Expected behaviour

What should happen is Nullgram automatically closes itself and the 'Official' icon appears as the app's icon in the Android launcher (i.e. home screen and app drawer).

### Actual behaviour

What happens instead is Nullgram automatically closes itself and the 'Default' icon (i.e. the new 'Null' icon) appears as the app's icon in the Android launcher (i.e. home screen and app drawer).
Please note that this bug does not occur for the icons 'Icon 1', 'Icon 2', 'Icon 3', 'Icon '4' and 'Icon 5'.

### Smartphone Information

- Device: Xiaomi Redmi Note 12 Pro 5G
- OS: Android 13
- Version: MIUI Global 14.0.8

### Nullgram Version

v11.4.2-e59b839 (1645201649) arm64 Based on Telegram 11.4.2 (5469)

### Version requirement

- [X] I am using latest debug CI version of Nullgram and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

[log-2024-11-24.txt](https://github.com/user-attachments/files/17894007/log-2024-11-24.txt)

**Comment by qwq233** [comment]
fixed in https://github.com/qwq233/Nullgram/commit/94fbf46268f67cf2cb58736fd8cb76b8df64efe3
