### ISSUE TITLE
[Bug] keepOnlineStatusAs 保持离线功能失效

### ISSUE THREAD

**Issue by Keeperorowner** [qwq233/Nullgram#342]
### Steps to reproduce

长按实验性功能，开启保持我的在线状态为离线

### Expected behaviour

在线状态为离线

### Actual behaviour

别人查看我的账号任然显示在线

### Smartphone Information

一加Ace3
ColorOS15

### Nullgram Version

v11.4.2-preview-7dcceff (1645201656)

### Version requirement

- [X] I am using latest debug CI version of Nullgram and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

[log-2024-12-16.txt](https://github.com/user-attachments/files/18144013/log-2024-12-16.txt)

**Comment by qwq233** [comment]
拦截markStoryAsRead会不会一直unread天天提醒烦死你啊

**Comment by qwq233** [comment]
那行 我抽空改了

**Comment by qwq233** [comment]
你等我明天看看好吧 我直接从TLRPC入手

**Comment by qwq233** [comment]
> @qwq233 你看一下，应该是有几个方法没有处理 org.telegram.messenger.MessagesController里有个markDialogAsRead方法 这个是上传消息已读状态的

你story隐身是怎么坏的 TL_stories_readStories 已经被处理过了

**Comment by qwq233** [comment]
> > @qwq233 你看一下，应该是有几个方法没有处理
> > org.telegram.messenger.MessagesController里有个markDialogAsRead方法 这个是上传消息已读状态的
> 
> 找到了completeReadTask 是这个方法，把这个方法拦截就不会上传消息已读状态了

这个和动态隐身没什么关系的

**Comment by qwq233** [comment]
你可能对这个功能有什么误解 这个只针对story

**Comment by qwq233** [comment]
> > 你可能对这个功能有什么误解 这个只针对story
> 
> 这个和story没关系，但是已读别人的消息，会暴露自己的最后在线时间呀，那保持离线状态就相当于失效了呀

如果你说keepOnlineStatus，是否在线是看客户端主动发出的account.updateStatus这个方法，例如熄屏时就会主动发送你offline了，最后在线时间我不清楚具体是怎么判断，但是这不是这个功能关注的重点。

下面有文档说明
https://core.telegram.org/method/account.updateStatus

**Comment by qwq233** [comment]
**这不是这个功能关注的重点**

**Comment by qwq233** [comment]
这个功能不关注“最后上线时间”，而是“是否在线”，麻烦审下题。

**Comment by qwq233** [comment]
显然，控制最后上线时间是极其困难的，因为我相信绝大部分人都不止会使用一个客户端/一台设备。除非你只在一台设备上使用Nullgram否则几乎不可能控制。anyway，我不打算处理，你硬要处理就自己上Xposed吧。
