### ISSUE TITLE
[功能请求] 希望可以增加当用户聊天接收新消息时，过滤某些敏感词(骂人赌博等)消息的功能。

### ISSUE THREAD

**Issue by YIRUIJIE** [qwq233/Nullgram#35]
### Why do you think you need this feature

在某些用户私聊时会有一些广告、赌博、色情或骂人的词语等，希望可以过滤(不显示)用户发来的包含敏感词的消息，减少部分私聊用户的骚扰等。

### Describe the solution you'd like

在某些用户私聊时会有一些广告、赌博、色情或骂人的词语等，希望可以过滤(不显示)用户发来的包含敏感词的消息，减少部分私聊用户的骚扰等。

**Comment by qwq233** [comment]
私聊的时候吗你指
