### ISSUE TITLE
[Bug] Application crash after system update. 

### ISSUE THREAD

**Issue by VCStardust** [qwq233/Nullgram#45]
### Steps to reproduce

Just open app from launcher.

### Expected behaviour

App works properly.

### Actual behaviour

Crash immediately.
Throws `java.lang.UnsatisfiedLinkError`

### Smartphone Information

- Device: Redmi K30 Pro (lmi)
- OS: Android 11 (crDroid 7.21)
- (Kernel?) Version: 4.19.234

### Nullgram Version

v8.9.3-preview-3cadedb (1645200792)

### Version requirement

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

Taken from MatLog: [logcat.txt](https://github.com/qwq233/Nullgram/files/9367722/logcat.txt)

And system it's own report: 
```
msg: java.lang.UnsatisfiedLinkError: No implementation found for void org.telegram.tgnet.ConnectionsManager.native_setJava(boolean) (tried Java_org_telegram_tgnet_ConnectionsManager_native_1setJava and Java_org_telegram_tgnet_ConnectionsManager_native_1setJava__Z)
stacktrace: java.lang.UnsatisfiedLinkError: No implementation found for void org.telegram.tgnet.ConnectionsManager.native_setJava(boolean) (tried Java_org_telegram_tgnet_ConnectionsManager_native_1setJava and Java_org_telegram_tgnet_ConnectionsManager_native_1setJava__Z)
	at org.telegram.tgnet.ConnectionsManager.native_setJava(Native Method)
	at org.telegram.messenger.ApplicationLoader.onCreate(ApplicationLoader.java:285)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1204)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6721)
	at android.app.ActivityThread.access$1300(ActivityThread.java:238)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:200)
	at android.os.Looper.loop(Looper.java:286)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by qwq233** [comment]
Did you install the arm64 version of nullgram?

**Comment by VCStardust** [comment]
Yes

**Comment by qwq233** [comment]
try this
https://github.com/qwq233/Nullgram/suites/7855713974/artifacts/332861928

**Comment by VCStardust** [comment]
Not solved, and it looks like the same version as the one already installed

**Comment by qwq233** [comment]
there's a signature verification on Nullgram.so did you modify the apk file?

**Comment by VCStardust** [comment]
Nope, I use CorePatch so it can be installed even if the signatures are different

**Comment by qwq233** [comment]
no, the signature verification won't do anything with the installation. but if you modify it, it will crash the jni.

anyway, there's another way to fix it that is download it from play store

**Comment by qwq233** [comment]
![image](https://user-images.githubusercontent.com/20317838/185305070-0d0dbf55-7fe8-4052-a9fe-033cb51ba844.png)

the log shows that the signature verification failed, so either you modified Nullgram, or your rom moved the PackageManager stuff and the signature verification failed

**Comment by VCStardust** [comment]
Maybe I have to uninstall it before install it in Google Play Store. 
Another app had the same problem and works after uninstall and reinstall from the apk, but it could keep data when uninstalling.

**Comment by qwq233** [comment]
anyway i have to close this issue cuz it seems to be a problem with your rom

**Comment by VCStardust** [comment]
OK, thanks for your help!
Just a suggestion, maybe add `android:hasFragileUserData` would be better so that no data will lost during reinstallation

**Comment by qwq233** [comment]
@VCStardust Nullgram's data is sensitive and related to the security of Telegram accounts, so I don't think I will do this. sorry

**Comment by VCStardust** [comment]
Strangely, I uninstalled, restarted, and then installed from Google Play, and it still won't open with the same error as above.

**Comment by VCStardust** [comment]
[logcat.txt](https://github.com/qwq233/Nullgram/files/9384973/logcat.txt)

Seems I know what's going on. (line 27)
I'll update the module tomorrow and try again.
Also, logs should use the program's PID as the filter, not "Nullgram", otherwise some of them will be missed.
