### ISSUE TITLE
[Bug] Notification bar does not change color according to background color shade

### ISSUE THREAD

**Issue by wuhang2003** [qwq233/Nullgram#69]
### Steps to reproduce

1. Go to _Settings_（设置）
2. Go to _Chat Settings_（主题与样式）
3. Click on _Browse Themes_（浏览主题）
4. Switch to a theme with a bright background color. (Such as Arctic)（北极）

### Expected behaviour

Like this screenshot (from official Telegram)
![Screenshot from official Telegram](https://user-images.githubusercontent.com/108316419/209472831-d6a29f0f-7ea9-40d2-be06-da5995ccbd30.png)

### Actual behaviour

This screenshot (from Nullgram), notification bar text does not change color according to background color shade.
![Screenshot from Nullgram](https://user-images.githubusercontent.com/108316419/209472931-978daeea-820d-4492-b860-6362af7a8459.png)

### Smartphone Information

- Device: Redmi K40 Pro
- OS: MIUI 13 (Android 12)

### Nullgram Version

v9.2.2.df376fc
Only this CI version has bug.

### Version requirement

- [X] I am using latest debug CI version of QAuxiliary and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

Maybe not need log

**Comment by qwq233** [comment]
https://github.com/qwq233/Nullgram/commit/41902468726db6d3a8dc357807c6aa79c3f831c2

fixed in next ci build

**Comment by wuhang2003** [comment]
No fix in next CI version
更版本了还是这样
![Screenshot_2022-12-26-08-08-08-604_com github android](https://user-images.githubusercontent.com/108316419/209485331-789e10cd-076e-4567-bbda-dcb7a7948917.jpg)

**Comment by qwq233** [comment]
@wuhang2003 关掉暗黑模式再打开试试

**Comment by wuhang2003** [comment]
> @wuhang2003 关掉暗黑模式再打开试试

看交流群回复，有视频
目前奇怪的是仅深色模式才会自动变色
