### ISSUE TITLE
[Bug] Some dynamic stickers cannot be previewed

### ISSUE THREAD

**Issue by reiuyfan** [qwq233/Nullgram#94]
### Steps to reproduce

1.Add sticker pack https://t.me/addstickers/Animated_Round_Pretty_Cat
2.To send stickers
3.See this dynamic sticker pack cannot be previewed

### Expected behaviour

Dynamic sticker pack can be previewed

### Actual behaviour

Dynamic sticker pack cannot be previewed

### Smartphone Information

Device: Xiaomi Poco F3
OS: Android 13
Version: 4.19.274-InfiniR_Alioth_v2.47//68d555f0ab92

### Nullgram Version

v9.5.4-preview-3b48113 (1645200988) 

### Version requirement

- [X] I am using latest debug CI version of Nullgram and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

https://github.com/reiuyfan/log/blob/main/logcat_03-19-2023_00-54-46.txt

**Comment by qwq233** [comment]
在主菜单有个*省电模式* (*Power Saving*) 检查是否开启

**Comment by reiuyfan** [comment]
> 在主菜单有个_省电模式_ (_Power Saving_) 检查是否开启 默认当你电力低于10%就会开启 这是tg官方的毛病

已经确认选择了总是关闭

**Comment by qwq233** [comment]
有没有修改override performance detect这个功能的选项
在Nullgram Settings->General->底部

**Comment by qwq233** [comment]
具体是什么表现呢，无法预览是指什么都没有，还是不会动态播放
我这边没法复现主要

**Comment by reiuyfan** [comment]
> 具体是什么表现呢，无法预览是指什么都没有，还是不会动态播放 我这边没法复现主要

不会动态播放，长按之后也没有任何反应

**Comment by qwq233** [comment]
@reiuyfan 有没有可能是网络问题呢，是只有这个sticker pack不会还是所有的都会呢

**Comment by reiuyfan** [comment]
> @reiuyfan 有没有可能是网络问题呢，是只有这个sticker pack不会还是所有的都会呢

网络是正常的，是一部分不能动态播放，可以的如 https://t.me/addstickers/SiameseCatLive ，不能的如 https://t.me/addstickers/CapooEmojiAnimated1

**Comment by qwq233** [comment]
我这边排查半天也没查出所以然
主要我这边是正常的，实在无法复现，暂且修不了，可能是个例因为也没听到其他人反馈
